/**
 * Trinity Protocol Configuration for Wedding Invite Project
 * Generated by Trinity Integration Script
 */

const config = {
    // Project metadata
    name: "Wedding Invite Event Management System",
    version: "2.0.0",
    description: "Multi-tenant event management system with RSVP enhancements",
    
    // Trinity validation settings
    validation: {
        strictMode: false,  // Allow gradual adoption
        skipPatterns: [
            "node_modules/**",
            "dist/**",
            "build/**",
            "__tests__/archived/**",
            "packages/canvastack/trinity/**"  // Skip self-validation
        ],
        testCoverage: {
            minimum: 70,  // Realistic target for existing project
            exclude: ["*.config.js", "*.test.js"]
        }
    },

    // Integration settings
    integration: {
        hooks: {
            preCommit: false,    // Disabled for initial integration
            prePush: false,      // Disabled for initial integration
            midDev: true,        // Enable for development feedback
            comprehensive: true   // Enable for full validation
        },
        reporting: {
            console: true,
            json: true,
            html: false  // Disable HTML for now
        }
    },

    // Project structure mapping
    structure: {
        src: "./src",
        tests: "./__tests__",
        docs: "./docs",
        database: "./database",
        scripts: "./scripts"
    },

    // RSVP Enhancement specific settings
    rsvpEnhancement: {
        phase: "FASE_2",
        trinityCompliant: true,
        features: [
            "real-time-tracking",
            "analytics-dashboard", 
            "notification-system",
            "multi-tenant-support"
        ]
    }
};

module.exports = config;
